### ISSUE TITLE
InvocationTargetException (IOException: can't read from InputStream)

### ISSUE THREAD

**Issue by dotStart** [dotStart/Beacon#17]
Insert a clear and concise description of the issue you are experiencing.

**Reproduction Steps**
1. Open a port
2. Terminate the network connection while the request is in flight

**Expected Behavior**
Report the error in a proper dialog for starters. Existing port registrations should remain in tact in order to retry a renew within the next cycle. The lease timeout should be raised to 3x or 4x the refresh period in order to facilitate support for intermediate connection problems.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Application Version: 3.0

**Additional Context**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787) ~[Beacon.exe:?]
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670) ~[Beacon.exe:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[Beacon.exe:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[Beacon.exe:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[Beacon.exe:?]
	at javafx.scene.Node.fireEvent(Node.java:8879) ~[Beacon.exe:?]
	at javafx.scene.control.Button.fire(Button.java:200) ~[Beacon.exe:?]
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206) ~[Beacon.exe:?]
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274) ~[Beacon.exe:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[Beacon.exe:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[Beacon.exe:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[Beacon.exe:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[Beacon.exe:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[Beacon.exe:?]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851) ~[Beacon.exe:?]
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579) ~[Beacon.exe:?]
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849) ~[Beacon.exe:?]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588) ~[Beacon.exe:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397) ~[Beacon.exe:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[Beacon.exe:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434) ~[Beacon.exe:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390) ~[Beacon.exe:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433) ~[Beacon.exe:?]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556) ~[Beacon.exe:?]
	at com.sun.glass.ui.View.notifyMouse(View.java:942) ~[Beacon.exe:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[Beacon.exe:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[Beacon.exe:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[Beacon.exe:?]
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[Beacon.exe:?]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[Beacon.exe:?]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784) ~[Beacon.exe:?]
	... 55 more
Caused by: java.io.IOException: can't read from InputStream
	at net.mm2d.upnp.internal.message.HttpMessageDelegate$Companion.readLine(HttpMessageDelegate.kt:302) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.message.HttpMessageDelegate$Companion.access$readLine(HttpMessageDelegate.kt:269) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.message.HttpMessageDelegate.readStartLine(HttpMessageDelegate.kt:216) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.message.HttpMessageDelegate.readData(HttpMessageDelegate.kt:204) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpResponse.readData(HttpResponse.kt) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpResponse$Companion.create(HttpResponse.kt:136) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpClient.writeAndRead(HttpClient.kt:144) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpClient.doRequest(HttpClient.kt:125) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpClient.post(HttpClient.kt:104) ~[Beacon.exe:?]
	at net.mm2d.upnp.HttpClient.post(HttpClient.kt:88) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionInvokeDelegate.invoke(ActionInvokeDelegate.kt:111) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionInvokeDelegate.invoke(ActionInvokeDelegate.kt:92) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionInvokeDelegate.invoke(ActionInvokeDelegate.kt:49) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionImpl.invokeCustomSync(ActionImpl.kt:49) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionImpl$invokeInner$1.invoke(ActionImpl.kt:63) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.impl.ActionImpl$invokeInner$1.invoke(ActionImpl.kt:22) ~[Beacon.exe:?]
	at net.mm2d.upnp.internal.thread.ExecuteFunctionKt$toRunnable$1.run(ExecuteFunction.kt:19) ~[Beacon.exe:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	... 1 more
```

**Comment by dotStart** [comment]
Raygun report https://app.raygun.com/crashreporting/27ce4ol/errors/4805720841 has more details about the error
