### ISSUE TITLE
2.1.2 Crashes Upon Attemtping to Start the Port Mapper

### ISSUE THREAD

**Issue by kinker31** [dotStart/Beacon#2]
Whenever I attempt to run Beacon 2.1.2, the program loads up until "Starting Port Mapper" in which the program stops and gives me the following error report:

Beacon Error Report
===================
Version: 2.1.2
Date: 2019-07-30T23:50:26.531895-05:00
Java Version: 12.0.2
Java Architecture: amd64
Operating System: Windows 10 (10.0)

Stack Trace:
------------
java.lang.NullPointerException
	at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109)
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93)
	at javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene.preferredSize(Scene.java:1748)
	at javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.stage.Window.show(Window.java:1189)
	at javafx.stage.Stage.show(Stage.java:273)
	at tv.dotstart.beacon.controller.SplashController$initialize$2.invoke(SplashController.kt:78)
	at tv.dotstart.beacon.controller.SplashController$initialize$2.invoke(SplashController.kt:40)
	at tv.dotstart.beacon.preload.Preloader$invoke$1$5.run(Preloader.kt:120)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by kinker31** [comment]
UPDATE: Never mind, turns out I was running an outdated version of the program, as 2.1.4 works perfectly fine for me! (At least for now)
